<?php
/**
 * StackTest.php
 *
 * PhpStorm
 *
 * @author: xielin
 */
namespace Phpunit;

/**
 * Class StackTest
 * @package Phpunit
 */
class StackTest extends \PHPUnit_Framework_TestCase
{
    public function testLoad()
    {
        $this->assertTrue(true);

    }


    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public static function tearDownAfterClass()
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }




}
